import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Dragon Hacks 2024</title>
        <meta name="description" content="Drexel Dragon Hack 2024, Welcome to 10th edition of Dragon Hacks, Register below!" />
        <link rel="icon" href="/vercel.ico" />
      </head>

      <body className={inter.className}>{children}</body>
    </html>
  )
}
